apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/nmirasch/konflux-components-dev?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "rpms/microshift-gitops/***".pathChanged() || ".tekton/konflux-components-dev-ms-rpm-push.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: test-rpms-builds
    appstudio.openshift.io/component: konflux-components-dev-ms-rpm
    pipelines.appstudio.openshift.io/type: build
  name: konflux-components-dev-ms-rpm-on-push
  namespace: nmirasch-tenant
spec:
  params:
  - name: ociStorage
    value: quay.io/redhat-user-workloads/nmirasch-tenant/konflux-components-dev-ms-rpm:on-pr-{{revision}}
  - name: package-name
    value: microshift-gitops
  - name: context
    value: rpms/microshift-gitops
  - name: path-context
    value: rpms/microshift-gitops
  - name: context-path
    value: rpms/microshift-gitops
  - name: specfile
    value: microshift-gitops.spec
  - name: git-url
    value: "{{ source_url }}"
  - name: revision
    value: "{{ revision }}"
  - name: target-branch
    value: "{{ target_branch }}"
  - name: hermetic
    value: "true"
  - name: build-architectures
    value:
    - aarch64
    - x86_64
#  - name: script-environment-image
#    value: "quay.io/redhat-user-workloads/nmirasch-tenant/konflux-components-dev-builder@sha256:9efb61c49d241b3597c1289b42ecb5e9ba9de48126bf101c51b93bdadb1215e4"
  - name: pre-build-script-content
    value: |
      #!/usr/bin/env bash
      set -euxo pipefail
      
      echo "--- Preparing to access source artifact CHANGED7--- "
      echo "--- SOURCE_ARTIFACT_URL: ${SOURCE_ARTIFACT_URL} --- "
      echo "--- cat microshift-gitops.spec: ---"
      
      cat microshift-gitops.spec
      
      CLEAN_SOURCE_URL=${SOURCE_ARTIFACT_URL#oci:}
      
      echo "Waiting for manifest to be available for ${CLEAN_SOURCE_URL}..."
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: "https://github.com/nmirasch/rpmbuild-pipeline.git"
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/build-rpm-package.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-konflux-components-dev-ms-rpm
  workspaces:
  - name: workdir
    persistentVolumeClaim:
      claimName: "{{pvc_name}}"
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}